### ISSUE TITLE
Supervisor should be able to open students' documents

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#100]
![image](https://user-images.githubusercontent.com/7829415/35485272-c5c558a0-0465-11e8-8556-f555a21da6a2.png)

In this table, the supervisor should be able to right-click on a document and see the menu with the options for show comments and view etc....
Also, I forgot to mention when we talked, there should be a spot where it says who is the mentor of the opened user, else the supervisor will not be able to know whom he needs to give the feedback to.

**Comment by michalchemo** [comment]
https://prnt.sc/i758wx
https://drive.google.com/file/d/1qACgw2saV744iWjrlB06I3kub2RRkwYJ/view

Added
