### ISSUE TITLE
The user student (that's the username) isn't on any of the list in the admin page

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#101]
The user was created using the free 2 weeks trial.
EDIT: I figured that one out. After editing the user its role is changed to לקוח which means he's not a student anymore. It is fixed when you edit again and change the role to "Student".
The first edit doesn't have to change anything besides the name. It will still change the role to לקוח. I tested this twice on newly created users, changed the name and the user broke.

**Comment by michalchemo** [comment]
its wordperss default.
when you change user name you must check all fields.

**Comment by gur111** [comment]
And is there no way to make sure the edit page will load the current active settings for that user? It doesn't make much sense that some settings will load as default unless you make sure to change them EVERYTIME you edit ANYTHING.
