### ISSUE TITLE
On FireFox when at the admin dashboard, the menues of the site's pages are not collapsed

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#103]
Also, the two tabs don't show properly. The calendar information also shows some undefined stuff and the page doesn't support it generally very well.
![image](https://user-images.githubusercontent.com/7829415/36250606-007e652e-1247-11e8-9918-0427c09013d2.png)

And down in the on the same page:
![image](https://user-images.githubusercontent.com/7829415/36250620-0c4f31bc-1247-11e8-9f88-ff904bfd9138.png)

**Comment by michalchemo** [comment]
http://prntscr.com/ijugeg

**Comment by gur111** [comment]
It's still not working for me.
![image](https://user-images.githubusercontent.com/7829415/36909531-e95c83c4-1e46-11e8-8c75-e025afb1e24a.png)
I've also checked to make sure that adblock is off and I used incognito so no cache would apply.

**Comment by michalchemo** [comment]
tried in 3 admin users
http://prntscr.com/inii1m

**Comment by gur111** [comment]
Seems to be fixed. Don't know what happened. I tried it myself now and it's working fine.
