### ISSUE TITLE
Sorting by זמן שנותר לתגובה doesn't work properly

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#106]
It doesn't move down in priority replied comments and instead keep them at the top. Thus the comments that require attention may stay at the bottom.
Checked it on the user amir-mentor
![image](https://user-images.githubusercontent.com/7829415/36250542-ca9d4736-1246-11e8-905c-42b06ef08bfe.png)

**Comment by michalchemo** [comment]
http://prntscr.com/ijsgeb
