### ISSUE TITLE
In the notification area of mentors - middle clicking (or right-click -> open in new tab) will cause the notification to not mark itself as done

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#107]
If you open a notification in a new tab it will not mark the comment as viewed. Only when you click a comment to view it in the same window.
Also when right clicking and copying the link doesn't mark it as done. Only normal click.
Also there should probably be a warning at the top of the notification panel that to make comments on assignment disappear you need to click on them even if it seems not to do anything as this is the only way I found to make them seem as read.

**Comment by michalchemo** [comment]
done.
