### ISSUE TITLE
הצג סימניות will not show bookmarks and will only show נעצים

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#110]

**Comment by michalchemo** [comment]
this is what it suppose to do.
you have 2 options to select from user book

**Comment by gur111** [comment]
I only see one option from user dashboard. I see הצג סימניות. Shouldn't it
show סימניות instead of what it's currently showing (נעצים)?

**Comment by michalchemo** [comment]
@gur111 
we discussed it over the  phone and decided to keep it with admin pins.
Am I remembering it correctly?

**Comment by gur111** [comment]
I don't remember that but maybe I'm wrong. There should be a place that you
see סימניות, otherwise what is the point of סימניות of you can't quickly
find them?

**Comment by gur111** [comment]
As we agreed with Amir (putting it here so we know where we were), the show bookmarks will show bookmarks (סמניות) instead of נעצים.

**Comment by michalchemo** [comment]
https://prnt.sc/infnpf
added as discussed

**Comment by gur111** [comment]
Using Chrome:
![image](https://user-images.githubusercontent.com/7829415/37049595-ffa8123e-2179-11e8-8915-df2a7757ae5c.png)
I only see a change looking at documents that aren't the main book. The main book still shows the נעצים.

**Comment by michalchemo** [comment]
Was a misunderstanding.
now fully done (I hope)
http://prntscr.com/io12su
