### ISSUE TITLE
Double clicking to open a נעץ before the rest of the נעצים will load causes a bug

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#118]
If you open a נעץ (without saving, just double clicking), then waiting to rest of the נעצים to load, then you click cancel on the נעץ you created the נעץ will still be there and will show "undefined" in the content.
Take note that this only happens when there are other נעצים on the page.
![image](https://user-images.githubusercontent.com/7829415/36793012-dbdb4a4e-1ca4-11e8-915e-52188a0d38cf.png)

**Comment by michalchemo** [comment]
I tried with many pages, nothing has happend,
Besides
Its on admin side only - it dosent mean anything even if its happening.

**Comment by gur111** [comment]
Fair enough
