### ISSUE TITLE
User Dashboard menus should allow middle click to open in a new tab

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#121]
We should probably go back to the non JS menus. It's more user-friendly and intuitive, it will be one thing less to explain.

**Comment by michalchemo** [comment]
are you serious right now?
this last 2 things just added are NOT bug.
its maybe somthing you can add later
but you cannot describe this as a bug
not with this deadline, time, budget and first requirements.

Addition that i'll be happy to discuss when we get to it.
apply for both this and issue #120

**Comment by gur111** [comment]
Sorry. Put bug label accidentally. You're right, it should have the label "add" or more "change back". Though I've only added this now because it only now went back to the old menus. It was fine for 2 months or so.

**Comment by michalchemo** [comment]
החזרתי לתפריט הזה
https://prnt.sc/ie1f45
