### ISSUE TITLE
Bugs with default value to editing a נעץ fields

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#125]
When editing a נעץ, then saving with/without and editing another נעץ, the changes will seem to take effect but deleting the new נעץ is impossible and after a refresh, the first נעץ is the one that was edited. That means an admin needs to refresh after each save. 
I think it's one bug, after editing a נעץ there are many strange effects to the page. Things that weren't touched and suddenly editing. A source נעץ with a different name then a destination one (It shouldn't be possible to both give a name and point to another נעץ).
I didn't test it on comments, I hope there isn't a similar bug there.

**Comment by gur111** [comment]
DONE

**Comment by michalchemo** [comment]
Tried it and all was there before refreshing
also in comments didnt face any issue.

about refresh
if its just for delete pin purpose?

**Comment by gur111** [comment]
I closed the issue because Amir and I talked and he said he's the only admin and he can live with it
