### ISSUE TITLE
Amir doesn't get notifications to his email from the site

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#13]

**Comment by deldnm012** [comment]
new signup, subscription and transaction email sent to his email address

**Comment by gur111** [comment]
New signup we just checked and it doesn't appear in his inbox. I recall Michal saying something about two types of admins and that it might be the cause.

**Comment by deldnm012** [comment]
Working now, all emails are appears in inbox

**Comment by gur111** [comment]
I still can't see anywhere a notification for a new user who registered for the free package: http://authedge.co.il/register/free-package/
Please check again.
EDIT: He does get notifications to his email. Closed.
