### ISSUE TITLE
About page responsiveness should crop the picture from the right

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#18]
So it looks good on phones and other smaller devices.

**Comment by gur111** [comment]
Really narrow devices should not show Amir's picture as it looks bad on a narrow screen

**Comment by michalchemo** [comment]
חושבת שעדכנתי
תוכל לוודא?
אם לא אודה להסבר

**Comment by michalchemo** [comment]
we need this as 2 seperate images
Amir as PNG
and the backgrouns without any crop

**Comment by gur111** [comment]
What's going on with this one? Table view still looks bad.

**Comment by michalchemo** [comment]
https://prnt.sc/in4icm

**Comment by gur111** [comment]
Now it's worse. This is how it looks on my 21:9 1080p monitor:
![image](https://user-images.githubusercontent.com/7829415/37050051-7cee98de-217b-11e8-9034-9deefcf08386.png)
This is 16:9 1080p monitor (native, not emulated):
![image](https://user-images.githubusercontent.com/7829415/37050192-e1bbaea0-217b-11e8-93e5-d850835e1195.png)

And in tablet mode, it does look fine but there's a big white part at the bottom (Both emulated at I don't have an actual tablet to test it on):
Landscape:
![image](https://user-images.githubusercontent.com/7829415/37050102-a477166a-217b-11e8-86f6-a1e02126bf37.png)
Portrait:
![image](https://user-images.githubusercontent.com/7829415/37050120-b3eae144-217b-11e8-8ba5-849267514bf9.png)

**Comment by michalchemo** [comment]
changed descktop view as well.

**Comment by gur111** [comment]
It still looks bad on my laptop (720p screen). I didn't test it on all resolutions but I think it will be good enough. Worst case they'll have a little trouble to read.
