### ISSUE TITLE
There is no way to remove mark on contact us form

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#23]
I think the bug is that there is no CSS ID as looked for and also no element assigned to that ID. The ID I'm referring to is: mepr-account-subscriptions

**Comment by michalchemo** [comment]
done

**Comment by gur111** [comment]
I still have the error even after hard reload

**Comment by deldnm012** [comment]
Done, Remove mark if value is entered

**Comment by gur111** [comment]
Sorry. I don't understand.
I mean that you can't remove the marks from the dot:
![image](https://user-images.githubusercontent.com/7829415/34453655-7944d18c-ed62-11e7-956f-bcf06d2880a0.png)

**Comment by deldnm012** [comment]
Done
