### ISSUE TITLE
Add picture in the first screen in online coaching 

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#26]
Add picture of comment (dialog box) in the gray window (the only one missing content)
Also add נעץ to the third picture that has the table of contents. Just to show there's a link funtionality

**Comment by gur111** [comment]
Also add נעץ to the third picture that has the table of contents.

**Comment by deldnm012** [comment]
http://authedge.co.il/wp-content/uploads/2017/11/ScreensImage_1420.jpg

This is whole image

**Comment by gur111** [comment]
I'm working on it. Don't worry about it. I will do this one.

**Comment by michalchemo** [comment]
changed this one. Orit sent me the img
