### ISSUE TITLE
Add jump to page box and move Next/Previous buttons to be bigger (more noticeable)

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#37]

**Comment by michalchemo** [comment]
http://prntscr.com/hsf7rm
design and suggestions are welcomed here

**Comment by gur111** [comment]
According to Amir, input box right under the numbers in the middle.
Also contain the text "למעבר לעמוד: " and a button that says "עבוד לעמוד".

**Comment by deldnm012** [comment]
Done, Please Check

**Comment by gur111** [comment]
As student the whole jump to page and the numbers themselves don't show. Only as admin it shows.
EDIT: We found out that on the user Romy Romy it does show. Although on amir-mentor it doesn't and also not on amir-student.
user: amir-mentor
pass: amir-mentor

P.S. Amir says  it looks amazing and great job on the design.

**Comment by deldnm012** [comment]
Working Now
