### ISSUE TITLE
Double clicking inside a text box shouldn't open new bookmark/נעץ window but like normally allow to select a word in the text

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#4]
When you click on a comment box it opens a new window for bookmarks. This can be unexpected for users.

**Comment by michalchemo** [comment]
firefox only
currently there isnt a solution for it when usiign mozilla
https://github.com/mozilla/geckodriver/issues/661
https://bugzilla.mozilla.org/show_bug.cgi?id=1385476
