### ISSUE TITLE
Allow Amir to edit plans' page content

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#42]
Like here: http://authedge.co.il/register/free-package/
I don't see how he can edit the page's content.
Also I don't really understand what the /online-track-a page is used for as well as /plan-a-dashboard

**Comment by michalchemo** [comment]
you can change the content from here :
http://authedge.co.il/wp-admin/post.php?post=766&action=edit
 or from related package http://prntscr.com/hsr6dx
