### ISSUE TITLE
Complex bug with comments and pins

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#43]
This is a complicated one (to explain)
When you hover on comment it opens the window with the content of the comment. When you hover first on a pin then go to comment, the pin stays opened and the comment window appears. Only now the pin's window shows the content of the comment as well. Both the comment and the pin show the same comment dialog
![image](https://user-images.githubusercontent.com/7829415/34359278-3f3c5bfa-ea5f-11e7-8cf6-1a79e06e445f.png)

**Comment by gur111** [comment]
Also to close the pin's dialog you need to click several times elsewhere on the screen.

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
Perfect
