### ISSUE TITLE
Amir's user isn't admin anymore. What happened?

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#45]
Why does it happen to often. 
I think Amir may have clicked on the register for free trial.

**Comment by michalchemo** [comment]
just dont add any purchase with this user.
if you want i can show you how to un-do it in DB

**Comment by gur111** [comment]
I think I remember how to do it through the DB but I don't have the credentials. No matter. Now I have my own admin so I can use it to recover Amir's account if it happens once again. CLOSED
