### ISSUE TITLE
In the notifications' area the text "הספר שלך" should be replaced with "כאן"

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#47]

**Comment by michalchemo** [comment]
where exactly?

**Comment by gur111** [comment]
When the user or mentor receive notification. 
REMOVED IMAGE
Correction. Amir decided he just wants to add the word כאן at the end. Just so it's clear to the user that clicking will take him/her to exactly the right spot.

**Comment by gur111** [comment]
Sorry for the confusion. The format should be "{person-name} הגיב על {name-of-file} כאן". Just for your understanding, in English it's "{person-name} commented on {name-of-file} here"

**Comment by deldnm012** [comment]
Please Check this - http://prntscr.com/huri5u

**Comment by gur111** [comment]
Perfect
