### ISSUE TITLE
When student is logged in he can click on where the buttons should be in נעץ dialog and "edit" and "delete" it

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#49]
It doesn't really edit and shows back after refresh but it's weird that it seemed to be possible.

**Comment by deldnm012** [comment]
In which page exactly?

**Comment by gur111** [comment]
Log in as a user, go to the first page. Hoven on a pin (the blue flags). Then you can hover on the place the admin would be seeing the Delete button and see it yourself.
![image](https://user-images.githubusercontent.com/7829415/34438843-31c97368-ecb2-11e7-984f-abc308771e4d.png)

**Comment by deldnm012** [comment]
Done, http://prntscr.com/huq1fb
