### ISSUE TITLE
Make the document of the book undeletable

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#50]

**Comment by michalchemo** [comment]
Done
when try to delete:
http://prntscr.com/hsr42c

working on design for all of those

**Comment by gur111** [comment]
Now I need to QA this. I changed assignee to myself.

**Comment by gur111** [comment]
Ok. I think you need to make the message disappear after a few seconds. Also, we need to make sure it's forbidden on the server's side as well. So we don't run into unfortunate mistakes.

**Comment by gur111** [comment]
Ok. I think you need to make the message disappear after a few seconds. Also, we need to make sure it's forbidden on the server's side as well. So we don't run into unfortunate mistakes.

**Comment by deldnm012** [comment]
message disappeared after a few seconds and server side and client side validation added, Done
