### ISSUE TITLE
Documents Tab enhancements

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#51]
Also show error message when the document is anything but PDF or WORD. Also maybe show a message in upload page for that.

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
Great job on that. Can you merge the two tabs "המסמכים שלי" and "Docs Storage"? The Upload button should automatically recognise what type of document it is and allow the user to view/edit it accordingly. 
Also, Amir and I really like the way you use implemented the menu. Instead of right click it should show in the merged tabs and maybe even in the "סטטוס מסמכים, הערות ותגובות" the same type of menu.
Download is "הורדה" in Hebrew.

**Comment by gur111** [comment]
Can you merge the upload button into one? I think it's more convinient for users if they don't have to think what type of files they are going to upload and the server will decide in which section it needs to put the uploaded file. 
Also, the docs section (for word documents) should have the title: "מסמכי וורד לאחסון וצפייה בלבד" (It means word documents for storage and view only.

**Comment by deldnm012** [comment]
Hi merging two section with one upload button is not possible technically

**Comment by gur111** [comment]
Ohh. OK. Then can you remove docx file type from the first section. It
should only accept pdf

**Comment by deldnm012** [comment]
Done, user side(Student Role)
