### ISSUE TITLE
Document Right Click Menu for Links

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#52]

**Comment by michalchemo** [comment]
why not?
its showing the links he added
the user.
when its new - its still empty

**Comment by gur111** [comment]
So for users there should be two tabs for this. One for links (which are what Amir inserts using the admin) and boomarks (which are what the users put). The bookmarks shouldn't be called links according to Amir.

**Comment by michalchemo** [comment]
user not seeing links of amir. 
only what he added

if he needs to see links of amir
than need to add this as additional  thing

**Comment by gur111** [comment]
By links I mean נעצים. That's the whole point of נעצים. That Amir gives users the ability to jump to the start of a chapter directly from the table of contents. Maybe it is needless to give users a concentrated table of the pins so I'm gonna ask Amir about it today. For now it's not priority so we can ignore it.
