### ISSUE TITLE
Show the name of the document that is about to be uploaded in upload documents page

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#53]

**Comment by deldnm012** [comment]
Done

**Comment by gur111** [comment]
I don't see it:
![image](https://user-images.githubusercontent.com/7829415/34519221-9da4d3b6-f08b-11e7-9eca-f489ac0a4f2a.png)
Maybe you didn't update mentor page and student page?

**Comment by gur111** [comment]
Any news?

**Comment by michalchemo** [comment]
https://prnt.sc/hxheed

**Comment by gur111** [comment]
The user should be able to validate that he selected the right file (before he clicked upload)

**Comment by michalchemo** [comment]
Done
http://prntscr.com/hzsdz2
