### ISSUE TITLE
Add transzilla to payment options in memberpress

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#55]

**Comment by gur111** [comment]
News?

**Comment by michalchemo** [comment]
its there...

**Comment by gur111** [comment]
Can you send screenshot? This is what I'm seeing:
![image](https://user-images.githubusercontent.com/7829415/34781544-c6c4c24e-f62e-11e7-8f9a-656cdc239e7d.png)
Then when I click on the אקטיב דיגיטל I get this:
![image](https://user-images.githubusercontent.com/7829415/34781582-dcc824be-f62e-11e7-8683-362195d4ca7c.png)

**Comment by gur111** [comment]
I checked and there's no change yet. Still don't see any option besides paypal. Maybe we want no option other than paypal there. Do tranzilla even offer subscriptions payments?
