### ISSUE TITLE
When creating new bookmark while there's another one in the page with a comment will show the comment on the newly created one as well until refresh

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#57]
EDIT: Amir says that bookmarks shouldn't even have comment option AND that they shouldn't be visible to mentors as they're private for each person.

If I have a bookmark in a page that has a comment. When I create another bookmark on the same page and hover over it, it will show the comments of the first bookmark (that was already present in the page).
The comment button will work but won't show the comments I send until refresh. 
If you have more than one bookmark present in the page with comments (before you create the new one) you will see on the new bookmark the comments of the last bookmark you hovered on. If you play with it you find that in some cases you see the comments of the first bookmark on the second on (not the newly created). Point is, it's a big mess right now.

**Comment by deldnm012** [comment]
Done
