### ISSUE TITLE
When right clicking on document and hovering over הצג קישורים the text split into two lines

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#58]
![image](https://user-images.githubusercontent.com/7829415/34385472-b76edc48-eb2b-11e7-898e-0a2206c66b43.png)
And when you hover on it:
![image](https://user-images.githubusercontent.com/7829415/34385479-c69a3e7e-eb2b-11e7-8a17-833def7ec6de.png)
It should stay as a single line all the time.

**Comment by deldnm012** [comment]
Done, Please Check

**Comment by gur111** [comment]
Perfect. thanks
