### ISSUE TITLE
Uploading different resolutions of profile photos cause weird results

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#60]
The best result is probably to let the user crop the picture to his liking after it is on the server and only then update it.
The problem is that some photos are too big. Some have a weird white bar on the side (like it shifted) and some both.
![image](https://user-images.githubusercontent.com/7829415/34386041-52db532a-eb2f-11e7-85be-221521f48a13.png)

**Comment by deldnm012** [comment]
Done, now user can crop the image with specific area

**Comment by gur111** [comment]
It's duplicated issue. so I'm closing this one
