### ISSUE TITLE
Neither mentor nor student can create a comment on document other than the book itself

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#61]
When the user/mentor creates a comment in הספר שלי everything is fine. The problem is when the user/mentor tries to create a comment on the user's other documents. The comment will seem to be created, there would even be a notification to the mentor on a new comment but when hovering on the comment it will show a forever loading loading sign
![image](https://user-images.githubusercontent.com/7829415/34386459-692f03d6-eb31-11e7-8ed3-ec995e7f4eb0.png)
 and after a refresh, it will disappear completely.

EDIT: Just figured that the loading forever also happens in the main book if the hovered comment doesn't have any replies and it does stop loading when it does. Maybe a bug with handling a zero-length array or getting null instead of the empty array. I see that for the student it happens much more and for mentor not as often if at all. I don't really understand this bug. I only see that under networking in the inspect element the response has something as null which is probably the cause. So server-side issue.

**Comment by deldnm012** [comment]
Loading sign disappear if no comment found

**Comment by gur111** [comment]
But what about adding comments to documents (PDFs) other than the book? The documents users upload? They disappear after reload.

**Comment by deldnm012** [comment]
Working in all documents

**Comment by gur111** [comment]
I receive confirmation from the server that the comment was created but after refreshing the document it disappears
![isseu with authedge comments](https://user-images.githubusercontent.com/7829415/34453786-40deb8aa-ed65-11e7-870f-385ab6529bcd.gif)

**Comment by deldnm012** [comment]
Working in all
test with your doc also : http://prntscr.com/hupq4k

**Comment by gur111** [comment]
Did you see the video I shared?

**Comment by deldnm012** [comment]
yes i saw, and please check this also
![jan-1-2018-12_32-pm](https://user-images.githubusercontent.com/5681697/34466177-cb8db9ba-eef0-11e7-926e-ccdef43648b0.gif)

**Comment by gur111** [comment]
I will.

On 1 Jan 2018 09:09, "Deval Mungalpara" <notifications@github.com> wrote:

yes i saw, and please check this also
[image: jan-1-2018-12_32-pm]
<https://user-images.githubusercontent.com/5681697/34466177-cb8db9ba-eef0-11e7-926e-ccdef43648b0.gif>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gur111/AuthEdge/issues/61#issuecomment-354639840>, or mute
the thread
