### ISSUE TITLE
Almost the enire website has a horizontal scrolling bar for like 3% or something

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#64]
When the screen is under 1920px wide (760 for example like my laptop) there is a horizontal scrollbar on the entire website. It doesn't reveal much when it's used and even if you zoom in the bar doesn't come to reveal more. It just stays there and reveals about the same.
![image](https://user-images.githubusercontent.com/7829415/34387144-2aae9c8a-eb35-11e7-90a3-2353af9fd373.png)
And after the zoom in
![image](https://user-images.githubusercontent.com/7829415/34387153-37a33040-eb35-11e7-958c-fe5b6347db36.png)

**Comment by deldnm012** [comment]
Done
