### ISSUE TITLE
When a comment is deleted the notification relating to that comment should be deleted as well

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#66]
Also, when trying to enter a notification for a deleted comment it gives a page that says "You don't have access to that page" (In Hebrew). It should probably show something like "Ooops. That comment doesn't exist anymore"

**Comment by deldnm012** [comment]
When comment deleted related notification automatic deleted and if annotation removed then its all comment and their notification removed

**Comment by gur111** [comment]
I don't see the removed notification. At least that's how it is for the mentor.
Try going into amir-mentor's notifications. Many of them bring you to the error page.

**Comment by deldnm012** [comment]
You have to reload the page, so notification removed from notification area

**Comment by gur111** [comment]
Did you check out the mentor user I gave? I did reload the page but it
still brings me to the error page on some of the comments.

**Comment by deldnm012** [comment]
This was because of old records but new one will not show there. howevere we are cleaning that table now from db directly.

**Comment by gur111** [comment]
K. Thanks
