### ISSUE TITLE
add soundcloud

### ISSUE THREAD

**Issue by michalchemo** [gur111/AuthEdge#71]
link inside popup with sound cloud link
we will add link to it inside the post, instead of current.
it will open it in blog main page:
https://authedge.co.il/%D7%91%D7%9C%D7%95%D7%92/

and at top post automativcally.

also,
add script to show page name - in posts as well - in elemntor
and not static text

**Comment by deldnm012** [comment]
sound cloud link play in popup Done
http://prntscr.com/hvfs6l

**Comment by gur111** [comment]
Soundcloud link doesn't work. Links to Soundcloud don't play although the request is received with 200 status.

**Comment by michalchemo** [comment]
https://prnt.sc/hzsvk2
add the link here:
http://prntscr.com/i0k149
