### ISSUE TITLE
paypal login

### ISSUE THREAD

**Issue by michalchemo** [gur111/AuthEdge#73]
pls add those, need to connect Amir's account and not ours

**Comment by gur111** [comment]
Payment doesn't work with memeberpress. It claims that the url from the site is wrong.

**Comment by michalchemo** [comment]
yes.
becuase we need to connect Amir's account
currently its working on SandBox mode

**Comment by gur111** [comment]
I know it was working in sandbox mode. I disabled sandbox and put Amir's
credentials there. I disabled sandbox both in WooCommerce and Memberpress

**Comment by michalchemo** [comment]
added succesfully, on live mode now
