### ISSUE TITLE
Issue with the second section of רשימת מנטורים

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#76]
1. It doesn't show the names of the assigned students for each of the mentors.

Change the second section:
* The dropdown should contain all the mentors.
* The button הוסף מנטור in the second section should be removed. It's already in the first section.
* After selecting a mentor in the dropdown all the mentor's students should show on the list below with the following values: Name, Time left to respond and a link to the user's workspace (More on that one later. But for now at least the rest except that link)

**Comment by michalchemo** [comment]
second section for mentor-10( super mentor )
and the second button used for add mentor-10, both roles are different so we have to give two different buttons
