### ISSUE TITLE
Unassigned issue

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#77]
I suspect that the ממתינים להשמת מנטור doesn't show all the unassigned students. Probably the issue is that after removing a mentor from user the value of mentor is 0 and before even assigning the value is undefined or someone of the sort.
![image](https://user-images.githubusercontent.com/7829415/34681512-c7634684-f4a4-11e7-9429-c04b52066ec5.png)

**Comment by michalchemo** [comment]
Done
https://prnt.sc/hzs2cc
(added code if mentor deleted then his/her users will be unassigned)
