### ISSUE TITLE
Mentor/student can't delete his comments on a user's book

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#80]
It seems to be deleted but comes back after refresh.
This is what I get:
{"error":1,"data":"","context_id":"162"} with status code 200

**Comment by gur111** [comment]
Now mentors can't delete comments as well from user's documents.

**Comment by gur111** [comment]
Now mentor can't

**Comment by michalchemo** [comment]
solved and working as expected

As said - it was server issue with cloudflare changes.

**Comment by michalchemo** [comment]
now done in admin book as well :)
