### ISSUE TITLE
When logged in as user the button איזור אישי gets you to the page you're at.

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#82]
If you're on the homepage it will link to the homepage. If you're in the book on a certain page it will link there.

**Comment by michalchemo** [comment]
it workes with no issue

**Comment by gur111** [comment]
Try using:
gur
1029384756
This is how the link looks like in inspect elements. Doesn't lead anywhere. Tested in both Firefox and Chrome
![image](https://user-images.githubusercontent.com/7829415/34948972-594b6aa0-fa17-11e7-80d3-3199cdfc3ed1.png)

**Comment by gur111** [comment]
I found that when changing the role of the memeber from לקוח to Student the issue is resolved (even when the subscription is expired the user can still enter his/her dashboard)

**Comment by michalchemo** [comment]
subscription activated so working now
