### ISSUE TITLE
Mentors see users that were unassigned (removed) to them as assigned 

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#83]
Tested with student Gur Telem (username: gur, password: 1029384756)
Mentor amir-mentor. Amir didn't get the notification on the comment "זנב"

**Comment by michalchemo** [comment]
working for me
try twice time got both time notification
http://prntscr.com/hzs8i8

**Comment by gur111** [comment]
![image](https://user-images.githubusercontent.com/7829415/34949158-fca95e28-fa17-11e7-8655-545f799675ef.png)
I'm not sure why the time left and time of creation is the same. I don't know if either is correct but I know it's going up (both).
Also, this picture shows that the notification isn't received even though the comment was placed:
![image](https://user-images.githubusercontent.com/7829415/34949266-46143006-fa18-11e7-848c-ff6082fb5216.png)

**Comment by gur111** [comment]
Ok. I think I know what the issue was. I saw that in the admin panel the user I sent the notification from was unassigned but from the mentor's page, it seemed that that user was assigned to the mentor.
