### ISSUE TITLE
After purchase of a subscription using paypal it isn't activated

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#84]
I paid for the least expensive subscription to test that it's working and it doesn't. After the purchase, I had an option to get back to the site and the site said "no active subscriptions".
![image](https://user-images.githubusercontent.com/7829415/34782494-91534e34-f631-11e7-9b05-82de4bafee00.png)
This page looks wrong as well. The orders tab is empty as well.
When I enter the user-dashboard and go to the subscriptions I see it empty

**Comment by gur111** [comment]
Checked today and there's no change regarding this one.
After force entering user-dashboard using handtyping the URL:
![image](https://user-images.githubusercontent.com/7829415/34987819-2cce0448-fac5-11e7-8bf3-d0e27f8bf2d6.png)

**Comment by michalchemo** [comment]
solved
http://prntscr.com/i25yiz
