### ISSUE TITLE
Amir's admin user always resets

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#86]
I'm not absolutely sure it's a bug but the user "amir" seems to reset itself. The name changes back to Michal Chemo (It's the second time I change that using the admin panel) and the role changes back to something else other than מנהל all the time (probably the 4th time I changed that, not counting your work on that).
Amir claims he didn't try to buy anything so I don't know what's going on. I hate to give vague bugs but that's what I have.

**Comment by michalchemo** [comment]
done 
needs to check in time
