### ISSUE TITLE
4 Desgin bugs

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#94]
![image](https://user-images.githubusercontent.com/7829415/35057679-5d480e44-fbbe-11e7-9bcc-bb6e20e90018.png)
Page 93
1. The names in the comment's comments are lowercased
2. The Time of the main comment is really weird. Although, time of replies is correct.
3. The order of the replies is absolutely wrong (look at the timestamps). When I tested it later with a minute difference in between replies it did work (I tested a completely new comment and replies).
4. In the long comment, the icons for edit and delete are positioned X from the bottom instead of X from the top.

**Comment by michalchemo** [comment]
changed
https://prnt.sc/i2zu7r
