### ISSUE TITLE
Time left in admin panel

### ISSUE THREAD

**Issue by gur111** [gur111/AuthEdge#97]
![image](https://user-images.githubusercontent.com/7829415/35471802-702083ac-036b-11e8-9838-22cabeb2af07.png)
I don't think it's a bug with the package itself because that one was solved already. Also the supermentor shows 0 as time left (Which also btw, maybe empty or something alike. 0 is not that bad though, just not perfect)

**Comment by michalchemo** [comment]
Havent we solved this already online?
I cant remmeber or see the issue now...

**Comment by gur111** [comment]
I don't see it now either. I'll close it for now and re-open later if needed
